// Mock AI responses for demo purposes
// In production, this would call your backend API with Gemini/OpenAI

export interface GeneratedContent {
  notes: string;
  flashcards: Array<{ question: string; answer: string }>;
  quiz: Array<{ question: string; options: string[]; correctAnswer: number }>;
}

export async function generateContentFromSource(
  type: "url" | "pdf" | "youtube" | "image",
  source: string | File
): Promise<GeneratedContent> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 2000));

  const sourceText = typeof source === "string" ? source : source.name;

  // Mock generated content based on type
  return {
    notes: `# Study Notes from ${type.toUpperCase()}

## Summary
This is AI-generated content from: ${sourceText}

## Key Points
- Main concept 1: Understanding the fundamentals
- Main concept 2: Practical applications
- Main concept 3: Advanced techniques

## Detailed Notes
Lorem ipsum dolor sit amet, consectetur adipiscing elit. This content would be generated by AI analyzing your ${type} content.

### Section 1
Important information extracted from the source material.

### Section 2
Additional insights and explanations.

## Conclusion
Summary of the main takeaways from this material.`,

    flashcards: [
      {
        question: "What is the main concept discussed?",
        answer: "The fundamental principles and their practical applications.",
      },
      {
        question: "How does this concept apply in practice?",
        answer: "Through various real-world examples and use cases.",
      },
      {
        question: "What are the key takeaways?",
        answer: "Understanding the core principles and their implementation.",
      },
    ],

    quiz: [
      {
        question: "What is the primary focus of this material?",
        options: [
          "Basic concepts",
          "Advanced techniques",
          "Practical applications",
          "All of the above",
        ],
        correctAnswer: 3,
      },
      {
        question: "Which approach is recommended?",
        options: [
          "Method A",
          "Method B",
          "Method C",
          "Combination approach",
        ],
        correctAnswer: 3,
      },
    ],
  };
}

export function getContentTypeIcon(type: string): string {
  const icons: Record<string, string> = {
    notes: "description",
    flashcards: "style",
    quiz: "quiz",
  };
  return icons[type] || "description";
}

export function getSourceTypeLabel(type: string): string {
  const labels: Record<string, string> = {
    url: "Website",
    pdf: "PDF Document",
    youtube: "YouTube Video",
    image: "Image/Screenshot",
  };
  return labels[type] || type.toUpperCase();
}
